# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Coverage

on:
  push:
    branches:
      # Push events to branches matching refs/heads/main
      - 'main'
      # Push events to branches matching refs/heads/release*
      - 'release*'
  # Trigger after PR was unlabeled
  pull_request:
    types:
      - unlabeled
  # Enables a manual trigger, may run on any branch
  workflow_dispatch:

# Do not cancel on push events
concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false # PRs will be canceled by the clang-format CI

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc13"
            compiler: "gcc-13"
            build: coverage
            build_type: Coverage

    steps:
      # How many commits do we need to fetch to also fetch the branch point?
      - name: Get fetch depth
        id: fetch_depth
        run: echo "depth=$(( ${{ github.event.pull_request.commits }} + 2 ))" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: sharg
          fetch-depth: ${{ steps.fetch_depth.outputs.depth }}
          submodules: true

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 125M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.16.9

      - name: Install gcovr
        run: |
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/${CC/gcc/gcov} 100
          pip install gcovr==6.0

      - name: Configure tests
        run: |
          mkdir sharg-build
          cd sharg-build
          cmake ../sharg/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                                  -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                                                  -DSHARG_VERBOSE_TESTS=OFF \
                                                  -DSHARG_COVERAGE_PARALLEL_LEVEL=2
          make -j2 gtest_build yaml-cpp

      - name: Build tests
        env:
          CCACHE_IGNOREOPTIONS: "-fprofile-abs-path"
          GCOV: ${{ github.workspace }}/sharg/.github/workflows/scripts/gcov.sh
        run: |
          ccache -z
          cd sharg-build
          make -k -j2
          ccache -sv

      - name: Submit coverage build
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/sharg-build/sharg_coverage.xml
          root_dir: ${{ github.workspace }}/sharg
